### ISSUE TITLE
socket.connect captures OSError only?

### ISSUE THREAD

**Issue by wangdino** [mfoc/Monitor-Internet-Connection#7]
Hello, thanks for sharing the code!

Question here:
https://github.com/mfoc/monitor-internet-connection/blob/3383f8b88225eb0125d58fd01911398110298ade/monitor_internet_connection.py#L114

Why is only OSError captured here?

In cases like when the network cable is unplugged, or if the router is reset, `socket.connect` will return a `socket.error`

Maybe add something like:
```
except socket.error as error:
    print(error)
    return False
```
to the code?

**Comment by mfoc** [comment]
Hi Wangdino,

Thank you very much for your feedback and comment.  I am both humbled and delighted that people find value in my program.

With regard to your specific concern to check for the exception socket.error in addition to the exception OSError, since Python version 3.3, the exceptions socket.error, EnvironmentError, IOError, WindowsError, select.error and mmap.error have been merged into OSError, as documented in [https://docs.python.org/3/library/exceptions.html#OSError](https://docs.python.org/3/library/exceptions.html#OSError)

Given that the documentation for monitor-internet-connection clearly states the minimum Python version required is Python 3.6, your concern has already been addressed.

Once again, I appreciate the time you took to comment.  Have a great day.

Martin

**Comment by wangdino** [comment]
Thanks a lot for the reply!

You're absolutely correct. I was running the code on a RPi and in `rc.local` I forgot to use `python3` instead of `python` which invokes Python 2.7.16 - Oops
